# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'kakaoLoginTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kakaoLoginTest
    pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
    pod 'KakaoSDKAuth'  # 카카오 로그인
    pod 'KakaoSDKUser'  # 사용자 관리

  target 'kakaoLoginTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kakaoLoginTestUITests' do
    # Pods for testing
  end

end
